### ISSUE TITLE
ReferenceError: context is not defined

### ISSUE THREAD

**Issue by gutenye** [stubailo/graphql-anywhere#1]
```
/Users/guten/a/node_modules/graphql-anywhere/lib/src/index.js:85
    var result = resolver(fieldName, rootValue, args, context);
                                                      ^

ReferenceError: context is not defined
    at executeField (/Users/guten/a/node_modules/graphql-anywhere/lib/src/index.js:85:55)
    at /Users/guten/a/node_modules/graphql-anywhere/lib/src/index.js:26:31
    at Array.forEach (native)
    at executeSelectionSet (/Users/guten/a/node_modules/graphql-anywhere/lib/src/index.js:23:29)
    at graphql (/Users/guten/a/node_modules/graphql-anywhere/lib/src/index.js:12:12)
    at Object.<anonymous> (/Users/guten/a/graphql-anywhere.js:5:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

graphql-anywhere version is '0.1.3'

**Comment by stubailo** [comment]
Thanks for reporting! This was a new thing that we didn't have in apollo-client before, so naturally it was the thing I forgot to test :]

Should be fixed in `0.1.4`.
